"""Tables of the NCT-CRC-HE-100K -> CRC-VAL-HE-7K replication, rebuilt from saved artifacts only.

Registered in PROTOCOL.md ("Independent-cohort replication"). Reads
results/2026-09-15_nct/descriptor_metrics.csv (nct_descriptor.py) and the YOLO
runs of runs/2026-09-15_nct (run.py through suite.py), and writes to
results/2026-09-15_nct:

- metrics.csv: one row per method, budget and seed on the 7,180 test patches;
- summary.md: macro-F1 and G-mean as mean [min-max] over the five seeds,
  paired differences to the primary method and per-class recall;
- paired.csv and recall.csv.

Run from colorectal_histology_classification/ with the cnn venv:
    cnn/.venv/bin/python comparison/nct_report.py
"""
import json
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
NCT = ROOT / "cache/nct"
RUNS = ROOT / "runs/2026-09-15_nct"
OUT = ROOT / "results/2026-09-15_nct"
PRIMARY = "gabor_svm"
METHODS = ("gabor_svm", "svm_tuned", "nearest_centroid", "pmd_l3", "yolo11n_random", "yolo11n")
LABELS = {"gabor_svm": "Gabor+CIELAB, RBF-SVM (C = 1)", "svm_tuned": "Gabor+CIELAB, tuned RBF-SVM",
          "nearest_centroid": "Gabor+CIELAB, nearest centroid", "pmd_l3": "Gabor+CIELAB, PMD (L = 3)",
          "yolo11n_random": "YOLO11n-cls, scratch", "yolo11n": "YOLO11n-cls, ImageNet"}
SCENARIOS = ("few1", "few2", "few5", "few10", "few20")


def markdown(frame):
    if frame.empty:
        return "No results."
    fmt = lambda x: f"{x:.3f}" if isinstance(x, float) else str(x)
    return "\n".join(["| " + " | ".join(map(str, frame.columns)) + " |", "| " + " | ".join("---" for _ in frame.columns) + " |"]
                     + ["| " + " | ".join(fmt(x) for x in row) + " |" for row in frame.itertuples(index=False, name=None)])


def main():
    manifest = json.loads((NCT / "manifest.json").read_text())
    names = manifest["class_names"]
    n = len(names)
    descriptor = pd.read_csv(OUT / "descriptor_metrics.csv")
    undefined = descriptor[descriptor.status != "complete"][["method", "scenario", "seed", "error"]]
    rows = [r for r in descriptor[descriptor.status == "complete"].to_dict("records")]
    failures = []
    for folder in sorted(RUNS.glob("nct_*__*__seed*")):
        config = json.loads((folder / "config.json").read_text())
        status = json.loads((folder / "status.json").read_text()) if (folder / "status.json").exists() else {}
        if status.get("status") != "complete":
            failures.append(dict(run=folder.name, status=status.get("status"), error=status.get("error", "")))
            continue
        test = json.loads((folder / "summary.json").read_text())["test_clean"]
        saved = np.load(folder / "eval/test_clean/predictions.npz")
        cm = np.zeros((n, n), dtype=int)
        np.add.at(cm, (saved["y_true"].astype(int), saved["y_pred"].astype(int)), 1)
        recall = np.diag(cm) / np.maximum(cm.sum(1), 1)
        history = json.loads((folder / "history.json").read_text())
        rows.append(dict(method=config["method"], scenario=config["scenario"].removeprefix("nct_"), seed=config["seed"],
                         status="complete", epochs=len(history.get("epoch", [])),
                         **{k: test[k] for k in ("macro_f1", "multiclass_gmean", "balanced_accuracy", "accuracy")},
                         **{f"recall_{name}": float(r) for name, r in zip(names, recall)}))
    frame = pd.DataFrame(rows)
    frame = frame[frame.method.isin(METHODS)]
    OUT.mkdir(parents=True, exist_ok=True)
    frame.to_csv(OUT / "metrics.csv", index=False)

    expected = {(m, s, seed) for m in METHODS for s in SCENARIOS for seed in manifest["seeds"]}
    present = set(zip(frame.method, frame.scenario, frame.seed))
    missing = sorted(expected - present - set(zip(undefined.method, undefined.scenario, undefined.seed)))

    sections = ["# NCT-CRC-HE-100K to CRC-VAL-HE-7K replication", "",
                "Generated by `comparison/nct_report.py`. Registered in `../../PROTOCOL.md` (\"Independent-cohort replication\"). Test set: all 7,180 patches of CRC-VAL-HE-7K; nine classes; center crop 150×150. Values: mean [min–max] over seeds 42–46.", "",
                f"Patches per class — train (union of the selected images): {manifest['counts']['train']}; validation: {manifest['counts']['val']}; test: {manifest['counts']['test']} (order {names}). Exact pixel duplicates: {manifest['exact_pixel_duplicates']}.", "",
                f"Completeness: {len(frame)} results; undefined: {len(undefined)}; failed runs: {len(failures)}; missing: {len(missing)}.", ""]
    if len(undefined):
        sections += ["Undefined results (expected for the PMD with one image per class):", "", markdown(undefined), ""]
    if failures:
        sections += ["Failed runs:", "", markdown(pd.DataFrame(failures)), ""]
    if missing:
        sections += ["Missing results: " + ", ".join(map(str, missing)), ""]

    for metric, title in (("macro_f1", "Macro-F1"), ("multiclass_gmean", "Multiclass G-mean"), ("balanced_accuracy", "Balanced accuracy")):
        stats = frame.groupby(["scenario", "method"])[metric].agg(["mean", "min", "max", "count"])
        table = stats.apply(lambda s: f"{s['mean']:.3f} [{s['min']:.3f}–{s['max']:.3f}]" + ("" if s["count"] == len(manifest["seeds"]) else f" (n={int(s['count'])})"), axis=1)
        table = table.unstack("method").reindex(SCENARIOS)[[m for m in METHODS if m in set(frame.method)]].fillna("--")
        table.index = [s.removeprefix("few") for s in table.index]
        sections += [f"## {title}", "", markdown(table.rename(columns=LABELS).reset_index().rename(columns={"index": "images/class"})), ""]

    paired_rows = []
    wide = frame.pivot_table(index=["scenario", "seed"], columns="method", values="macro_f1")
    for scenario in SCENARIOS:
        for other in METHODS:
            if other == PRIMARY or other not in wide.columns or scenario not in wide.index.get_level_values(0):
                continue
            part = wide.loc[scenario][[PRIMARY, other]].dropna()
            if part.empty:
                continue
            diff = part[PRIMARY] - part[other]
            paired_rows.append(dict(images_per_class=scenario.removeprefix("few"), other=other, seeds=len(diff),
                                    svm_minus_other_mean=diff.mean(), minimum=diff.min(), maximum=diff.max(),
                                    seeds_svm_better=int((diff > 0).sum())))
    paired = pd.DataFrame(paired_rows)
    paired.to_csv(OUT / "paired.csv", index=False)
    sections += ["## Paired macro-F1 difference: RBF-SVM (C = 1) minus each method, same seed", "", markdown(paired), ""]

    recall = frame.groupby(["scenario", "method"])[[f"recall_{c}" for c in names]].mean()
    recall.columns = names
    recall = recall.reset_index()
    recall.to_csv(OUT / "recall.csv", index=False)
    for scenario in ("few10", "few20"):
        part = recall[recall.scenario == scenario].drop(columns="scenario").set_index("method").reindex([m for m in METHODS if m in set(recall.method)])
        sections += [f"## Per-class recall with {scenario.removeprefix('few')} images per class (mean of seeds)", "",
                     markdown(part.rename(index=LABELS).reset_index()), ""]
    if "epochs" in frame:
        epochs = frame[frame.method.str.startswith("yolo")].groupby(["scenario", "method"]).epochs.agg(["min", "max"]).reset_index()
        sections += ["## YOLO training epochs (early stopping on the 450 validation patches)", "", markdown(epochs), ""]
    (OUT / "summary.md").write_text("\n".join(sections))
    print("\n".join(sections))


if __name__ == "__main__":
    main()
