"""Tables of the RBF-SVM campaign next to PolyGabor and the CNNs, rebuilt from saved artifacts only.

Reads runs/2026-09-15_svm (gabor_svm), runs/2026-09-12 (PolyGabor and CNNs,
registered campaign) and runs/2026-09-14_cpu (CPU-only CNN training, post-hoc
cost measurement), and writes CSV tables and summary.md to
results/2026-09-15_svm. The LOSO statistics reuse the functions of
loso_report.py, with the same 5,000 source-bootstrap draws (seed 123).

Run from colorectal_histology_classification/ with the cnn venv:
    cnn/.venv/bin/python comparison/svm_report.py
"""
import json
from pathlib import Path
import sys

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
from loso import MANIFEST, global_labels  # noqa: E402
from loso_report import DRAWS, confusion, macro_f1_present, pooled_metrics  # noqa: E402
from report import markdown_table, read  # noqa: E402

SVM, REGISTERED, CPU = "2026-09-15_svm", "2026-09-12", "2026-09-14_cpu"
OUT = ROOT / "results" / SVM
CNNS = ("resnet18", "resnet18_imagenet", "yolo11n_random", "yolo11n")
METHODS = ("gabor_svm", "polygarbor", "polygarbor_aug", *CNNS)
LOSO_METHODS = ("gabor_svm", "polygarbor", *CNNS)
SCARCE = ("few1", "few2", "few5", "few10", "few20", "few50", "few100", "full")
TRAIN_STAGES = ("build_model", "prepare_pipeline", "extract_features", "fit")


def runs(campaign, methods):
    """Completed, non-pilot runs of the given methods, with the fields used in the paper tables."""
    rows = []
    for folder in sorted((ROOT / "runs" / campaign).glob("*__*__seed*")):
        config, status = read(folder / "config.json", {}), read(folder / "status.json", {})
        if config.get("method") not in methods or status.get("status") != "complete" or config.get("pilot"):
            continue
        timing, resources = read(folder / "timings.json"), read(folder / "resources.json")
        base = dict(campaign=campaign, method=config["method"], scenario=config["scenario"], seed=config["seed"],
                    path=str(folder), train_seconds=sum(timing.get(s, {}).get("seconds", 0) for s in TRAIN_STAGES),
                    model_mb=read(folder / "model_size.json")["mb"], rss_peak_mb=resources["all"]["rss_mb_peak"])
        for evaluation, metrics in read(folder / "summary.json").items():
            rows.append(base | dict(evaluation=evaluation, **{k: metrics[k] for k in
                        ("macro_f1", "multiclass_gmean", "balanced_accuracy", "accuracy")}))
    return pd.DataFrame(rows)


def mean_range(frame, index, column, value="macro_f1"):
    stats = frame.groupby([index, column])[value].agg(["mean", "min", "max", "count"])
    table = stats.apply(lambda s: f"{s['mean']:.3f} [{s['min']:.3f}–{s['max']:.3f}]" if s["count"] > 1 else f"{s['mean']:.3f}", axis=1)
    return table.unstack(column)


def recall_from_predictions(path, n):
    saved = np.load(path)
    cm = confusion(saved["y_true"].astype(int), saved["y_pred"].astype(int), n)
    return np.diag(cm) / np.maximum(cm.sum(1), 1)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = json.loads(MANIFEST.read_text())
    names, folds = manifest["class_names"], manifest["folds"]
    n = len(names)
    frame = pd.concat([runs(SVM, ("gabor_svm",)), runs(REGISTERED, METHODS[1:])], ignore_index=True)
    frame.to_csv(OUT / "runs.csv", index=False)
    test = frame[frame.evaluation == "test_clean"]
    methods = [m for m in METHODS if m in set(test.method)]
    sections = ["# RBF-SVM on the descriptor: registered scenarios", "",
                f"Generated by `comparison/svm_report.py` from `runs/{SVM}` (gabor_svm), `runs/{REGISTERED}` (PolyGabor and CNNs) and `runs/{CPU}` (CPU-only CNN training cost). Values are test macro-F1 unless stated otherwise; `mean [min–max]` across seeds 42 and 43.", ""]

    scarce = test[test.scenario.isin(SCARCE)]
    order = {s: i for i, s in enumerate(SCARCE)}
    for metric, title in (("macro_f1", "Scarce labels: macro-F1"), ("multiclass_gmean", "Scarce labels: G-mean")):
        table = mean_range(scarce.dropna(subset=[metric]), "scenario", "method", metric)
        table = table.reindex(sorted(table.index, key=order.get))[[m for m in methods if m in table.columns]].reset_index()
        table.to_csv(OUT / f"scarce_{metric}.csv", index=False)
        sections += [f"## {title}", "", markdown_table(table.fillna("--")), ""]
    sections += ["PolyGabor without augmentation has no few1 result (the reference PMD implementation fails with one vector per class).", ""]

    noise_rows, imbalance_rows = [], []
    for method in methods:
        clean = test[(test.method == method) & (test.scenario == "full") & (test.seed == 42)]
        noisy = test[(test.method == method) & (test.scenario == "label_noise") & (test.seed == 42)]
        if len(clean) and len(noisy):
            noise_rows.append(dict(method=method, clean=clean.macro_f1.iat[0], noisy=noisy.macro_f1.iat[0],
                                   delta=noisy.macro_f1.iat[0] - clean.macro_f1.iat[0],
                                   gmean_clean=clean.multiclass_gmean.iat[0], gmean_noisy=noisy.multiclass_gmean.iat[0]))
        imbalanced = test[(test.method == method) & (test.scenario == "imbalance") & (test.seed == 42)]
        if len(imbalanced):
            recall = recall_from_predictions(Path(imbalanced.path.iat[0]) / "eval/test_clean/predictions.npz", n)
            imbalance_rows.append(dict(method=method, macro_f1=imbalanced.macro_f1.iat[0],
                                       multiclass_gmean=imbalanced.multiclass_gmean.iat[0],
                                       **{f"recall_{name}": float(r) for name, r in zip(names, recall)}))
    noise, imbalance = pd.DataFrame(noise_rows), pd.DataFrame(imbalance_rows)
    noise.to_csv(OUT / "label_noise.csv", index=False)
    imbalance.to_csv(OUT / "imbalance.csv", index=False)
    sections += ["## Label noise (20%, seed 42)", "", markdown_table(noise), "",
                 "## Class imbalance (tumor, stroma, complex and mucosa at 10%, seed 42)", "", markdown_table(imbalance), ""]

    robust = frame[(frame.scenario == "full") & frame.evaluation.str.startswith("test_")]
    robustness = robust.pivot_table(index="evaluation", columns="method", values="macro_f1", aggfunc="mean")
    robustness = robustness[[m for m in methods if m in robustness.columns]].reset_index()
    robustness.to_csv(OUT / "robustness.csv", index=False)
    sections += ["## Image perturbations (full training, mean of two seeds)", "", markdown_table(robustness), ""]

    labels = global_labels()
    sources = sorted(fold["test_source"] for fold in folds.values())
    parts = {}
    for campaign, selected in ((SVM, ("gabor_svm",)), (REGISTERED, LOSO_METHODS[1:])):
        for folder in sorted((ROOT / "runs" / campaign).glob("loso_*__*__seed*")):
            config, status = read(folder / "config.json", {}), read(folder / "status.json", {})
            if config.get("method") not in selected or status.get("status") != "complete" or config.get("pilot"):
                continue
            fold = folds[config["scenario"]]
            saved = np.load(folder / "eval/test_clean/predictions.npz")
            y, p = saved["y_true"].astype(int), saved["y_pred"].astype(int)
            if not np.array_equal(y, labels[fold["test"]]):
                raise RuntimeError(f"{folder.name}: test labels differ from {MANIFEST.name}")
            parts.setdefault((config["method"], config["seed"]), {})[fold["test_source"]] = (y, p)
    complete = {key: value for key, value in parts.items() if sorted(value) == sources}
    pooled_rows, recall_rows = [], []
    for (method, seed), by_source in sorted(complete.items()):
        y = np.concatenate([by_source[s][0] for s in sources])
        p = np.concatenate([by_source[s][1] for s in sources])
        metrics, recall = pooled_metrics(y, p, names)
        random_split = test[(test.method == method) & (test.scenario == "full") & (test.seed == seed)].macro_f1
        pooled_rows.append(dict(method=method, seed=seed, **metrics,
                                random_split_macro_f1=random_split.iat[0] if len(random_split) else None))
        recall_rows.append(dict(method=method, seed=seed, **dict(zip(names, recall.tolist()))))
    pooled, recalls = pd.DataFrame(pooled_rows), pd.DataFrame(recall_rows)
    pooled.to_csv(OUT / "loso_pooled.csv", index=False)
    recalls.to_csv(OUT / "loso_recall_per_class.csv", index=False)
    paired_rows = []
    draws = np.random.default_rng(123).integers(0, len(sources), size=(DRAWS, len(sources)))
    for seed in sorted({seed for method, seed in complete if method == "gabor_svm"}):
        svm = {s: confusion(*complete[("gabor_svm", seed)][s], n) for s in sources}
        for other in LOSO_METHODS[1:]:
            if (other, seed) not in complete:
                continue
            rival = {s: confusion(*complete[(other, seed)][s], n) for s in sources}
            stack_a, stack_b = np.stack([rival[s] for s in sources]), np.stack([svm[s] for s in sources])
            observed = macro_f1_present(stack_b.sum(0)) - macro_f1_present(stack_a.sum(0))
            boot = np.array([macro_f1_present(stack_b[d].sum(0)) - macro_f1_present(stack_a[d].sum(0)) for d in draws])
            fold_a = {s: macro_f1_present(rival[s]) for s in sources}
            fold_b = {s: macro_f1_present(svm[s]) for s in sources}
            paired_rows.append(dict(seed=seed, a=other, b="gabor_svm", macro_f1_b_minus_a=observed,
                                    source_bootstrap_ci_low=float(np.quantile(boot, .025)),
                                    source_bootstrap_ci_high=float(np.quantile(boot, .975)),
                                    folds_a_better=sum(fold_a[s] > fold_b[s] for s in sources),
                                    folds_b_better=sum(fold_b[s] > fold_a[s] for s in sources)))
    paired = pd.DataFrame(paired_rows)
    paired.to_csv(OUT / "loso_paired_svm_vs_others.csv", index=False)
    loso_summary = pd.DataFrame()
    if not pooled.empty:
        grouped = pooled.groupby("method")
        loso_summary = pd.DataFrame(dict(seeds=grouped.seed.count(), macro_f1=grouped.macro_f1.mean(),
                                         macro_f1_min=grouped.macro_f1.min(), macro_f1_max=grouped.macro_f1.max(),
                                         macro_f1_without_empty=grouped.macro_f1_without_empty.mean(),
                                         multiclass_gmean=grouped.multiclass_gmean.mean(),
                                         random_split_macro_f1=grouped.random_split_macro_f1.mean()))
        loso_summary["drop"] = loso_summary.random_split_macro_f1 - loso_summary.macro_f1
        loso_summary = loso_summary.reindex([m for m in LOSO_METHODS if m in loso_summary.index]).reset_index()
    sections += ["## Leave-one-source-out (5,000 pooled predictions)", "", markdown_table(loso_summary), "",
                 "Per-class recall, mean of the seeds:", "",
                 markdown_table(recalls.groupby("method")[names].mean().reindex([m for m in LOSO_METHODS if m in set(recalls.method)]).reset_index()
                                if not recalls.empty else recalls), "",
                 "Paired source bootstrap, difference = gabor_svm minus the other method:", "", markdown_table(paired), ""]

    cost_rows = []
    cpu_cnns = runs(CPU, CNNS)
    for method in LOSO_METHODS:
        source = frame if method in ("gabor_svm", "polygarbor") else cpu_cnns
        rows = source[(source.method == method) & (source.seed == 42) & (source.evaluation == "test_clean")] if not source.empty else source
        entry = dict(method=method, training_runs=SVM if method == "gabor_svm" else (REGISTERED if method == "polygarbor" else CPU))
        for scenario in ("few10", "full"):
            row = rows[rows.scenario == scenario] if len(rows) else rows
            entry[f"train_s_{scenario}"] = row.train_seconds.iat[0] if len(row) else None
            entry[f"rss_mb_{scenario}"] = row.rss_peak_mb.iat[0] if len(row) else None
        sizes = test[(test.method == method) & (test.scenario.isin(["few2", "full"]))].groupby("scenario").model_mb.mean()
        entry["model_mb_few2"], entry["model_mb_full"] = sizes.get("few2"), sizes.get("full")
        benchmark_dir = ROOT / "runs" / (SVM if method == "gabor_svm" else REGISTERED) / "edge" / f"{method}__cpu1"
        benchmark = read(benchmark_dir / "benchmark.json", {})
        entry["cpu1_median_ms"] = benchmark.get("median_ms")
        entry["cpu1_rss_mb"] = read(benchmark_dir / "resources.json", {}).get("all", {}).get("rss_mb_peak") if benchmark else None
        cost_rows.append(entry)
    cost = pd.DataFrame(cost_rows)
    cost.to_csv(OUT / "cost.csv", index=False)
    sections += ["## Cost (seed 42, CPU)", "", markdown_table(cost), "",
                 "Training time includes feature extraction (build, extraction and fit stages). RSS: peak resident memory of the whole training and evaluation process, sampled every 200 ms. CNN training cost comes from the CPU-only runs of 2026-09-14; PolyGabor and gabor_svm always run on the CPU. Model size at few2 and full: mean of two seeds. cpu1: fresh-process benchmark with one logical processor and one thread (median single-image latency and peak RSS).", ""]
    (OUT / "summary.md").write_text("\n".join(sections))
    print("\n".join(sections))


if __name__ == "__main__":
    main()
